### ISSUE TITLE
Upload hangs on 6mb files

### ISSUE THREAD

**Issue by andrewnakas** [SquareBeam/unity-aws-services#1]
Hello, I'm trying to upload 6mb text and also trying zip files to my aws bucket inside my android vr (pico) application. I find that when I try to upload large files around 6mb the app completely hangs while it's uploading. Sometimes it uploads successfully, other times the app hangs up and crashes, from what I assume is from too long of a frozen main thread as the upload is processing. Any insight on how I can get around this and get smooth uploading of larger files? I'm trying to zip these files but have a little trouble getting that done and need more testing, but the text upload just completely freezes with larger files. Smaller files do upload and the main thread freezes for a moment but the expected progress information still gets uploaded so I can see it working. When I upload big files progress seems to break and im just there in a frozen vr world. Any insight on how to remedy this? When I was using the /net examples, I was able to implement file transfer utility to do multipart uploads which seemed to help a little bit, but the async issues of that still were a problem. Thanks for the help with figuring this out.

**Comment by SquareBeam** [comment]
Hello, does this problem exists only in build, or could be replicated in Editor?

**Comment by SquareBeam** [comment]
@andrewnakas  I just tested on Pico G2 4K with 170Mb file and it is uploaded without blocking main thread. I slightly modified S3 Example scene to upload file from Application.persistentDataPath and then drop the file via USB

**Comment by SquareBeam** [comment]
@andrewnakas so did you have a chance to test in the way described above?

**Comment by SquareBeam** [comment]
Closed due to inactive

**Comment by andrewnakas** [comment]
Hey sorry, was super busy this wee and the tobii license was expired this
week but that just got sorted out, will test out tonight.
