### ISSUE TITLE
S3 Functions Error: ForcedScopedThreadAttach

### ISSUE THREAD

**Issue by maxcelar** [SquareBeam/unity-aws-services#2]
Hello!

Only the "List all Buckets" function works in the S3 example scene. The downloading and uploading results in 3 Errors:
1. "ForcedScopedThreadAttach can only be used from threads that are not already attached."
2. `Failure: SquareBeam.AWS.S3.S3Exception was thrown!
UnityEngine.Debug:LogError (object)
S3ExampleUsage/<>c__DisplayClass22_0:<Upload>g__OnDone|0 (SquareBeam.AWS.S3.S3Response) (at Assets/AWS/Services/S3/Example/S3ExampleUsage.cs:225)
SquareBeam.AWS.S3.S3API/<UploadObject>d__8:MoveNext () (at Assets/AWS/Services/S3/S3API.cs:283)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)`
3.
`Description: HTTP/1.1 403 Forbidden`
UnityEngine.Debug:LogError (object)
S3ExampleUsage/<>c__DisplayClass22_0:<Upload>g__OnDone|0 (SquareBeam.AWS.S3.S3Response) (at Assets/AWS/Services/S3/Example/S3ExampleUsage.cs:231)
SquareBeam.AWS.S3.S3API/<UploadObject>d__8:MoveNext () (at Assets/AWS/Services/S3/S3API.cs:283)
UnityEngine.SetupCoroutine:InvokeMoveNext `(System.Collections.IEnumerator,intptr)`

![Unity_2021-03-11_00-27-28](https://user-images.githubusercontent.com/4674620/110717861-c1076e80-8201-11eb-9288-75bde8d66b73.png)

The credentials are definitely correct.
I'm using Unity 2020.2.7f1 iOS platform

I would appreciate your help with this please.

**Comment by SquareBeam** [comment]
@MaxCelar trying to reproduce will back to you soon

**Comment by SquareBeam** [comment]
@MaxCelar  So I created new project on 2020.2.7f1 iOS platform, imported package, and set my test credentials, but it is still working for me, I expected that something breaks with web request on latest unity, but it seems ok.

Can you please contact with me privately squarebeamassets@gmail.com so we can share project details

**Comment by maxcelar** [comment]
> @MaxCelar So I created new project on 2020.2.7f1 iOS platform, imported package, and set my test credentials, but it is still working for me, I expected that something breaks with web request on latest unity, but it seems ok.
> 
> Can you please contact with me privately [squarebeamassets@gmail.com](mailto:squarebeamassets@gmail.com) so we can share project details

Thanks for a quick response. I will contact you privately.

**Comment by maxcelar** [comment]
@SquareBeam Hi! I tried to recreate the issue step by step, because I suspected "Best HTTP/2" package might be interfering, but when I restarted my computer the problem was resolved... It must have been something external.

I'll let you know if it happens again and I'll try to narrow it down.
Thank you for your help

**Comment by SquareBeam** [comment]
> @SquareBeam Hi! I tried to recreate the issue step by step, because I suspected "Best HTTP/2" package might be interfering, but when I restarted my computer the problem was resolved... It must have been something external.
> 
> I'll let you know if it happens again and I'll try to narrow it down.
> Thank you for your help

I will very much appreciate it if you rate the package
