### ISSUE TITLE
Hey - what parts of AWS ecosystem does this SDK support?

### ISSUE THREAD

**Issue by MnTronslien** [SquareBeam/unity-aws-services#3]
AWS has a number of services. Such as S3, DynamoDB, Cogito e.c.t. Which services are supported through this SDK?

**Comment by SquareBeam** [comment]
Hi,
S3, Lambda, EC2, Cognito are in development

вт, 20 квіт. 2021, 17:11 користувач MnTronslien ***@***.***>
пише:

**Comment by SquareBeam** [comment]
> AWS has a number of services. Such as S3, DynamoDB, Cogito e.c.t. Which services are supported through this SDK?

EC2, S3, Lambda. Cognito are in development
