### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by codiemorgan** [SquareBeam/unity-aws-services#5]
I am considering buying this asset - but I don't have any clear indication on weather this will work from within a WebGL build.

I created a stable wrapper around S3 for desktop and other platforms, but am unable to get it to work within a webGL build using Unity 2020.3.33.

Does this work well from within WebGL (using user/key for auth via code)?

**Comment by SquareBeam** [comment]
Hi, yes, but requires some extra step to do in bucket policy

вт, 31 трав. 2022, 13:58 користувач Codie Morgan ***@***.***>
пише:

**Comment by codiemorgan** [comment]
OK. Thanks. 

My boss has purchased the SDK for me so I do have access to it now.
The Policy instructions already mentions setting up "Full Access" for the user, which Im pretty sure I have already done.
However your guide specifies creating a bucket manually via the console.

Are your instructions enough to enable your api access to the creation/deletion of buckets by code? 
With my current configuration the .NET Api is already able to create/delete buckets as needed.
Or will there be some additional steps I need to follow?

**Comment by SquareBeam** [comment]
Hi, so you want to create and delete buckets via unity code? right?

чт, 9 черв. 2022, 10:04 користувач Codie Morgan ***@***.***>
пише:

**Comment by codiemorgan** [comment]
Yes. My  code needs to create/delete buckets only instead of relying on existing buckets created by hand.

**Comment by codiemorgan** [comment]
I have the S3 Full Managed policy.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*",
                "s3-object-lambda:*"
            ],
            "Resource": "*"
        }
    ]
}
```

However, every single request after CreateBucket fails with `403:forbidden`.

**Comment by SquareBeam** [comment]
You can DM me on Telegram https://t.me/marshaII_Iee I'll help you sort this
out faster

чт, 9 черв. 2022, 11:37 користувач Square Beam ***@***.***>
пише:

**Comment by SquareBeam** [comment]
Please DM in telegram I'll help to sort this out, since it's not very
comfortable to do via emails

чт, 9 черв. 2022, 13:02 користувач Square Beam ***@***.***>
пише:

**Comment by sabbirtkdr** [comment]
Hello @SquareBeam I am considering to buy this sdk as well. Could you tell if it will support authentication for WebGL build? I require to download models from s3 buckets using aws credentials. I am using the 2022 version of the unity

**Comment by SquareBeam** [comment]
Yes, it will support, its wont be so secure, since credentials is gonna be
stored in wasm build, unless you transfer those cred to client in another
way, but anyway yes, it will work

**Comment by sabbirtkdr** [comment]
Could you suggest what we can do regarding the credentials if we decide to use your sdk?

**Comment by SquareBeam** [comment]
You can have them embedded, you can build auth system using AWS Cognito

**Comment by nawangwe** [comment]
Hi @SquareBeam could you advise on how we can use Cognito through a webGL build? What should be placed in the redirect URL? And would it work or do we need to make some modifications to the code.

**Comment by SquareBeam** [comment]
Hi, In redirect URL in Cognito Setup should be your adress where WebGL
build is hosted. Unity will read queryParams (it should contain accessToken
after successful sign in)

**Comment by WhyWeiHan** [comment]
Hi @SquareBeam is there any part of this sdk was handling refresh token to prevent re-login using Cognito after token expiration?  I am using WebGL platform and faced the token expiration issue stated "CognitoAPI: Cache access token is expired"

**Comment by nawangwe** [comment]
@WhyWeiHan I've successfully introduced authorization code flow into the library, along with a token refresh mechanism. @SquareBeam let me know if you'd like to merge these changes into your lib.
