### ISSUE TITLE
Question: Does this asset support background uploads?

### ISSUE THREAD

**Issue by derwaldgeist** [SquareBeam/unity-aws-services#7]
We need a background upload feature for our iOS and Android apps. AWS official SDK supports this, via the `TransferUtility`. Is this supported by your asset?

**Comment by SquareBeam** [comment]
Hi, nope it doesn't, all comunication is done by Unity Web Request, but
it's nice feature, however it should be done as separated native plugin

**Comment by derwaldgeist** [comment]
Thanks for the fast response, highly appreciated! I am trying to build exactly such a plugin for our app right now. But I thought I might take a short-cut with your asset.
